### PR TITLE
expose externalURL to templates

### PR DESCRIPTION
**Pull request by ahmadalli**
this PR exposes `externalURL` from alertmanager webhook to the templates

### CODE REVIEW

**Comment by tlex** [comment]
Thank you for your PR. I've added a few changes in 6e174fe4cbc6612314649fe52052ff945424390e

After the [pipeline](https://gitlab.com/ix.ai/alertmanager-notifier/-/pipelines/229641408) runs through, I'll merge it to master.

**Comment by tlex** [comment]
You can give it a spin with `registry.gitlab.com/ix.ai/alertmanager-notifier:dev-master` or `ixdotai/alertmanager-notifier:dev-master`. If all works as expected, I'll create a new release by the end of the week.

**Comment by ahmadalli** [comment]
I've just tested it and works perfectly. I made this PR because I wanted to have alertmanager URL like the one that exists on alertmanager emails. Now I found out that another variable (`receiver`) is required in order to create that URL. I'll send another PR soon.

P.S. this is how alertmanager produces that URL:

https://github.com/prometheus/alertmanager/blob/193ebba04d1e70d971047e983a0b489112610460/template/default.tmpl#L2

**Comment by tlex** [comment]
Looking here https://prometheus.io/docs/alerting/latest/configuration/#webhook_config I can see the following alert structure for the webhook:

```json
{
  "version": "4",
  "groupKey": <string>,              // key identifying the group of alerts (e.g. to deduplicate)
  "truncatedAlerts": <int>,          // how many alerts have been truncated due to "max_alerts"
  "status": "<resolved|firing>",
  "receiver": <string>,
  "groupLabels": <object>,
  "commonLabels": <object>,
  "commonAnnotations": <object>,
  "externalURL": <string>,           // backlink to the Alertmanager.
  "alerts": [
    {
      "status": "<resolved|firing>",
      "labels": <object>,
      "annotations": <object>,
      "startsAt": "<rfc3339>",
      "endsAt": "<rfc3339>",
      "generatorURL": <string>       // identifies the entity that caused the alert
    },
    ...
  ]
}
```

I think it's safe to leave it like that.

**Comment by ahmadalli** [comment]
I'm not gonna change `external_url`. I'm just gonna expose `receiver` to the template and generate url on the template

**Pull request merged**
