### PR TITLE
Expose receiver to the templates

### PR DESCRIPTION
**Pull request by ahmadalli**
this completes the #10 in order to create better alertmanager URLs

### CODE REVIEW

**Review by tlex — CHANGES_REQUESTED** [review]
You need to add the receiver to the following files as well:
* https://github.com/ix-ai/alertmanager-notifier/blob/master/alertmanager-notifier/lib/utils.py#L55

Also, the https://github.com/ix-ai/alertmanager-notifier/blob/master/templates/markdown.md.j2 and https://github.com/ix-ai/alertmanager-notifier/blob/master/templates/text.j2 should remain consistent, so please modify the link in them as well

**Comment by ahmadalli** [comment]
I've fixed the consistency and added the receiver to utils.py file

**Comment by tlex** [comment]
Thanks for this. I'll take it for a spin on the `dev-branch` tag, to see the outcome

**Comment by tlex** [comment]
And this is how we discover bugs in other pieces of software. Looks like Gotify can't handle `#` in an URL. I'll merge it with an additional commit that reverts the changes to the URL in `markdown.md.j2`

**Review by tlex — APPROVED** [review]

**Comment by tlex** [comment]
After additional tests, it seems that jinja strips the `#`, not gotify. I've just gotten this on the `html.j2` template:

```
monitoring_alertmanager-telegram.1.x0g7ot6nqms0@docker-c    | <b>Generator</b>: <a href="https://prometheus.xxxREDACTEDxxx/graph?g0.expr=probe_success+%3D%3D+0&g0.tab=1">Prometheus Query</a>
monitoring_alertmanager-telegram.1.x0g7ot6nqms0@docker-c    | <b>Alertmanager URL</b>: <a href="https://alertmanager.xxxREDACTEDxxx//alerts?receiver=telegram-webhook">View Alerts on Alertmanager</a>
monitoring_alertmanager-telegram.1.x0g7ot6nqms0@docker-c    | 2020-12-14 20:28:05.669 DEBUG [notifiers.telegram_notify] True
```

I suspect this is because of https://github.com/ix-ai/alertmanager-notifier/blob/master/alertmanager-notifier/lib/utils.py#L59, which was introduced because of a strange behavior in how Telegram handles hashes.

I'll look for a solution to that.

**Comment by tlex** [comment]
As usual, once the [pipeline](https://gitlab.com/ix.ai/alertmanager-notifier/-/pipelines/229742957) is through, you can take it for a spin on the tag `dev-master`.

**Pull request merged**
